"""HTML export for estate sale pricing results."""

import html
from datetime import datetime, timezone
from pathlib import Path


def _format_price(price: float | None) -> str:
    if price is None:
        return "N/A"
    return f"${price:,.2f}"


def _confidence_badge(conf: str) -> str:
    colors = {
        "high": "#22c55e",
        "medium": "#eab308",
        "low": "#ef4444",
        "none": "#9ca3af",
    }
    color = colors.get(conf, "#9ca3af")
    stars = {"high": "\u2605\u2605\u2605", "medium": "\u2605\u2605\u2606", "low": "\u2605\u2606\u2606", "none": "\u2606\u2606\u2606"}
    return f'<span style="color:{color};font-weight:bold">{stars.get(conf, "\u2606\u2606\u2606")}</span>'


def export_html(
    sale_info: dict | None,
    items: list[dict],
    pricing: dict[str, dict],
    output_path: str | None = None,
) -> str:
    """Export results as a styled HTML report.

    Args:
        sale_info: Sale metadata dict.
        items: List of identified item dicts.
        pricing: Dict mapping item_id to pricing data.
        output_path: Optional file path to write to.

    Returns:
        HTML string.
    """
    title = "Photo Analysis Results"
    subtitle = ""
    if sale_info:
        title = html.escape(sale_info.get("title", "Unknown Sale"))
        loc = sale_info.get("location", "")
        dates = sale_info.get("sale_dates", [])
        subtitle = html.escape(f"{loc} — {', '.join(dates)}" if dates else loc)

    # Build table rows
    rows_html = []
    total_median = 0.0
    for item in items:
        ip = pricing.get(item["item_id"], {})
        median = ip.get("price_median")
        low = ip.get("price_low")
        high = ip.get("price_high")
        comps = ip.get("results_count", 0)

        name = html.escape(item.get("name", ""))
        category = html.escape(item.get("category", "").replace("_", " ").title())
        conf = item.get("confidence", "low")

        range_str = f"${low:,.0f}&ndash;${high:,.0f}" if low and high else "N/A"
        comps_str = f"{comps} sold" if comps else "no data"

        if median:
            total_median += median

        rows_html.append(f"""<tr>
            <td style="text-align:center">{_confidence_badge(conf)}</td>
            <td>{name}</td>
            <td>{category}</td>
            <td style="text-align:right">{_format_price(median)}</td>
            <td style="text-align:right">{range_str}</td>
            <td style="text-align:right">{comps_str}</td>
        </tr>""")

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — Estate Pricer Report</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 2rem; color: #1a1a1a; background: #fafafa; }}
  h1 {{ color: #1e40af; margin-bottom: 0.25rem; }}
  .subtitle {{ color: #6b7280; margin-bottom: 1.5rem; }}
  table {{ border-collapse: collapse; width: 100%; background: white; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
  th {{ background: #1e40af; color: white; padding: 0.75rem 1rem; text-align: left; }}
  td {{ padding: 0.5rem 1rem; border-bottom: 1px solid #e5e7eb; }}
  tr:hover {{ background: #f0f9ff; }}
  .summary {{ margin-top: 1.5rem; padding: 1rem; background: #eff6ff; border-radius: 0.5rem; }}
  .footer {{ margin-top: 1rem; color: #9ca3af; font-size: 0.85rem; }}
</style>
</head>
<body>
<h1>{title}</h1>
<div class="subtitle">{subtitle}</div>

<table>
<thead>
<tr>
  <th style="width:60px">Conf</th>
  <th>Item</th>
  <th style="width:120px">Category</th>
  <th style="width:100px;text-align:right">Median $</th>
  <th style="width:130px;text-align:right">Range</th>
  <th style="width:100px;text-align:right"># Comps</th>
</tr>
</thead>
<tbody>
{"".join(rows_html)}
</tbody>
</table>

<div class="summary">
  <strong>Total Estimated Value:</strong> {_format_price(total_median)} (median) &mdash; {len(items)} items identified
</div>

<div class="footer">Generated by Estate Pricer on {now}</div>
</body>
</html>"""

    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w") as f:
            f.write(doc)

    return doc
